### ISSUE TITLE
All keys deleted after Redis server rebooted unexpectedly

### ISSUE THREAD

**Issue by jarkkojasberg** [OrleansContrib/Orleans.Redis#19]
Redis server rebooted unexpectedly and all keys were deleted.

Following exception was thrown in every write operation after reboot:
`Exc level 0: StackExchange.Redis.RedisServerException: NOSCRIPT No matching script. Please use EVAL.
   at Orleans.Persistence.RedisGrainStorage.WriteToRedisAsync(IDatabaseAsync db, Object state, String etag, String key, String newEtag)
   at Orleans.Persistence.RedisGrainStorage.WriteStateAsync(String grainType, GrainReference grainReference, IGrainState grainState)
   at Orleans.Core.StateStorageBridge1.WriteStateAsync()`

It seems that logic attempts to migrate grain state every time when RedisServerException is thrown.
Is this a proper way to determine that state should be migrated?

When RedisServerException is thrown, delete and write commands are executed in the same transaction
and in this case write operation inside the transaction will fail. This exception is not caught in the code.

Redis transactions don't work the same way than in normal relational database.
Transactions are not going to rollback changes if one or more commands fails in transaction.

So reboot caused Redis server to clean all cached SHA:s for prepared scripts. Then server started to throw RedisServerException
in every write operation. This was handled as a old grain state and started migration. Delete and write commands were
executed in the same transaction. Only delete was executed successfully and all keys were deleted.

**Comment by SebastianStehle** [comment]
I think this is the default for redis. You have to turn on disk persistence

**Comment by jarkkojasberg** [comment]
We have configured RDB persistence for Redis server and also tested that data is restored from snapshot after reboot. If the persistence didn't work we should have lost all keys immediately when server was rebooted. Now keys were deleted gradually after reboot. I'm quite sure that the migration code in RedisGrainStorage.WriteStateAsync function is deleting keys from Redis server.

**Comment by SebastianStehle** [comment]
Yes, you are right. I should have read it more carefully. I think your observations are correct:

1. Not every RedisServerException is a migration problem.
2. Transactions are useless here.
3. Delete should not be used.
4. For migrations the key should just be overriden.

**Comment by ReubenBond** [comment]
Are you able to take a look at fixing this, @jarkkojasberg?

**Comment by f-i-x-7** [comment]
Recently our team encountered same issue with permanent receival of exception as @jarkkojasberg mentioned in 1st post until Orleans silo was restarted. Most probably the reason was Redis server restart too (I didn't perform a deep investigation). We have .RDB persistence enabled too. Fortunately, this was a test environment.
May be I will be able to prepare suggested fix. But I did not see any contributing guidelines in this repo. If there are any, please let me know.

**Comment by f-i-x-7** [comment]
Hello again,

As our team uses Orleans in production and we possibly will migrate some grains from ADO.NET/EF storage to Redis next year, we want to be sure in stable work of `RedisGrainStorage`. So one of my colleagues is going to fix this bug.

After discussion with him I've checked the code in `RedisGrainStorage` more carefully. It seems that migration logic from `WriteStateAsync()` can be safely removed because of 2 reasons:

1. Every grain at first reads state from storage. So if migration needed, it would be already performed during`ReadStateAsync()` call.
2. Migration logic in `WriteStateAsync()`, if executed, actually would fail. It uses the same Lua script as regular `WriteStateAsync()` operation. This script uses HGET command to retrieve Palyload and ETag. But for old grain storage format HGET would throw (something like "(error) ERR Error running script (call to f_6b1bf486c81ceb7edf3c093f4c48582e38c0e791): ERR Operation against a key holding the wrong kind of value").

So, as part of the bugfix, we are going just to remove migration logic from `WriteStateAsync()`.

@ReubenBond @SebastianStehle are you OK with that?
