### ISSUE TITLE
Problem supporting redis sentinel cluster

### ISSUE THREAD

**Issue by grendizeras** [OrleansContrib/Orleans.Redis#49]
We are experiencing problem with orleans clustering with redis when failover of redis server occurs. 
we have following setup:

` siloBuilder.UseRedisClustering(clusterOptions =>
 {
     clusterOptions.ConfigurationOptions=ConfigurationOptions.Parse(redisConnectionString);
 }`

where redisConnectionString is like "redis1:26739,redis:26739, serviceName=mymaster"

Problem is whenever one of servers stops, we get redis timeout errors, that is only fixed when application is being restarted manually.

As I could figure it out from source, RedisMembershipTable 
`   public async Task InitializeMembershipTable(bool tryInitTableVersion)
  {  
      _muxer = await _redisOptions.CreateMultiplexer(_redisOptions);
      _db = _muxer.GetDatabase();
....
` 

must be the reason, as it holds _db object which connected to old master redis server and never tries to reconnect. My proposition would be to listen for ConnectionMultiplexer.ConnectionFailed event and force multiplexer to reconnect to another redis instance, that is provided by sentinel cluster

**Comment by ReubenBond** [comment]
I spoke with Marc Gravell (SE.Redis maintainer) and he says the db "is a red herring" here, since it's merely a wrapper around the muxer. It might be worth opening/upvoting/pinging an issue on the SE.Redis repo to see if automated recovery can be a focal point for .NET 10. Otherwise, it seems that there is some ad-hoc recovery code in some consumer code to recreate the multiplexer if it detects too much failure. It might be worth borrowing similar code for this and the official Redis packages, in the dotnet/orleans repo. For reference, here is an example of recovery code: https://github.com/dotnet/aspnetcore/blob/dc68e3b6d51ba96191a58e3b9775b4d43358c30d/src/Caching/StackExchangeRedis/src/RedisCache.cs#L626. You can see how it's using a heuristic to determine whether the muxer needs to be destroyed and recreated.

**Comment by grendizeras** [comment]
> I spoke with Marc Gravell (SE.Redis maintainer) and he says the db "is a red herring" here, since it's merely a wrapper around the muxer. It might be worth opening/upvoting/pinging an issue on the SE.Redis repo to see if automated recovery can be a focal point for .NET 10. Otherwise, it seems that there is some ad-hoc recovery code in some consumer code to recreate the multiplexer if it detects too much failure. It might be worth borrowing similar code for this and the official Redis packages, in the dotnet/orleans repo. For reference, here is an example of recovery code: https://github.com/dotnet/aspnetcore/blob/dc68e3b6d51ba96191a58e3b9775b4d43358c30d/src/Caching/StackExchangeRedis/src/RedisCache.cs#L626. You can see how it's using a heuristic to determine whether the muxer needs to be destroyed and recreated.

Thanks for  sharing.
